[config]
default_to_workspace = false
skip_core_tasks = true

[tasks.build]
description = "Build with short messages"
command = "cargo"
args = ["build", "--message-format=short"]

[tasks.clippy]
description = "Run clippy checks"
command = "cargo"
args = ["clippy", "--message-format=short", "--all-targets", "--all-features", "--", "-D", "warnings"]

[tasks.check]
description = "Run cargo check"
command = "cargo"
args = ["check", "--message-format=short"]

[tasks.test]
description = "Run unit tests"
command = "cargo"
args = ["test", "--message-format=short"]

[tasks.strict-clippy]
description = "Run clippy checks in pedantic mode"
command = "cargo"
args = [
    "clippy",
    "--all-features",
    "--offline",
    "--message-format=short",
    "--",
    "--deny", "warnings",
    "--deny", "clippy::pedantic",
    "--deny", "clippy::nursery",
    "--allow", "clippy::wildcard_imports",
    "--allow", "clippy::used_underscore_binding",
    "--allow", "clippy::missing_docs_in_private_items",
    "--allow", "clippy::missing_panics_doc",
    "--allow", "clippy::missing_errors_doc",
    "--allow", "clippy::missing_safety_doc",
    "--allow", "clippy::doc_markdown",
]

[tasks.format]
description = "Check code formatting"
command = "cargo"
args = ["fmt", "--message-format=short"]

